config/routes.rb
EvergreenTest::Application.routes.draw do
  resources :hello_worlds

end

app/models/hello_world.rb
class HelloWorld < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hello_worlds_controller.rb
class HelloWorldsController < ApplicationController
  # GET /hello_worlds
  # GET /hello_worlds.xml
  def index
    @hello_worlds = HelloWorld.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hello_worlds }
    end
  end

  # GET /hello_worlds/1
  # GET /hello_worlds/1.xml
  def show
    @hello_world = HelloWorld.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hello_world }
    end
  end

  # GET /hello_worlds/new
  # GET /hello_worlds/new.xml
  def new
    @hello_world = HelloWorld.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hello_world }
    end
  end

  # GET /hello_worlds/1/edit
  def edit
    @hello_world = HelloWorld.find(params[:id])
  end

  # POST /hello_worlds
  # POST /hello_worlds.xml
  def create
    @hello_world = HelloWorld.new(params[:hello_world])

    respond_to do |format|
      if @hello_world.save
        format.html { redirect_to(@hello_world, :notice => 'Hello world was successfully created.') }
        format.xml  { render :xml => @hello_world, :status => :created, :location => @hello_world }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hello_world.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hello_worlds/1
  # PUT /hello_worlds/1.xml
  def update
    @hello_world = HelloWorld.find(params[:id])

    respond_to do |format|
      if @hello_world.update_attributes(params[:hello_world])
        format.html { redirect_to(@hello_world, :notice => 'Hello world was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hello_world.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hello_worlds/1
  # DELETE /hello_worlds/1.xml
  def destroy
    @hello_world = HelloWorld.find(params[:id])
    @hello_world.destroy

    respond_to do |format|
      format.html { redirect_to(hello_worlds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_worlds_helper.rb
module HelloWorldsHelper
end

app/views/hello_worlds/_form.html.erb
<%= form_for(@hello_world) do |f| %>
  <% if @hello_world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hello_world.errors.count, "error") %> prohibited this hello_world from being saved:</h2>

      <ul>
      <% @hello_world.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hello_worlds/edit.html.erb
<h1>Editing hello_world</h1>

<%= render 'form' %>

<%= link_to 'Show', @hello_world %> |
<%= link_to 'Back', hello_worlds_path %>

app/views/hello_worlds/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $("h1").click(function() {
      $(this).text("Fuck you");
    });
  });
</script>
<h1>Listing hello_worlds</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hello_worlds.each do |hello_world| %>
  <tr>
    <td><%= link_to 'Show', hello_world %></td>
    <td><%= link_to 'Edit', edit_hello_world_path(hello_world) %></td>
    <td><%= link_to 'Destroy', hello_world, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hello world', new_hello_world_path %>

app/views/hello_worlds/new.html.erb
<h1>New hello_world</h1>

<%= render 'form' %>

<%= link_to 'Back', hello_worlds_path %>

app/views/hello_worlds/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hello_world_path(@hello_world) %> |
<%= link_to 'Back', hello_worlds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EvergreenTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>